### ISSUE TITLE
Request backward compatibility with Linux kernel 6.6

### ISSUE THREAD

**Issue by brokestar233** [firelzrd/parallel-swapper#2]
### Problem Description  
 I tried building it on Linux kernel 6.6 but encountered errors. I backported the kfifo patch from kernel 6.16 along with some other patches. The compilation succeeded, but the system still fails to boot.

[Here](https://github.com/brokestar233/android_kernel_common_oneplus_sm8750/tree/kcompressd)'s my attempt.

### Environment  
- System: Android 15
- Kernel: 6.6.87
- Device: Oneplus13

### Observed Failure  
-  [x] **Compilation failure**
-  [x] **Runtime crash**
-  [ ] **Functionality broken** 

### Additional context  

1. Build log from when the kfifo patch from 6.16 and other patches weren't backported

```bash
In file included from ../arch/arm64/kernel/asm-offsets.c:10:
In file included from ../include/linux/arm_sdei.h:8:
In file included from ../include/acpi/ghes.h:5:
In file included from ../include/acpi/apei.h:9:
In file included from ../include/linux/acpi.h:13:
In file included from ../include/linux/resource_ext.h:11:
In file included from ../include/linux/slab.h:16:
In file included from ../include/linux/gfp.h:7:
In file included from ../include/linux/mmzone.h:26:
In file included from ../include/linux/kfifo.h:42:
In file included from ../include/linux/scatterlist.h:8:
In file included from ../include/linux/mm.h:33:
../include/linux/memremap.h:162:3: error: call to undeclared function 'is_zone_device_page'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  162 |                 is_zone_device_page(page) &&
      |                 ^
../include/linux/memremap.h:174:3: error: call to undeclared function 'is_zone_device_page'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  174 |                 is_zone_device_page(page) &&
      |                 ^
../include/linux/memremap.h:180:9: error: call to undeclared function 'is_zone_device_page'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  180 |         return is_zone_device_page(page) &&
      |                ^
In file included from ../arch/arm64/kernel/asm-offsets.c:10:
In file included from ../include/linux/arm_sdei.h:8:
In file included from ../include/acpi/ghes.h:5:
In file included from ../include/acpi/apei.h:9:
In file included from ../include/linux/acpi.h:13:
In file included from ../include/linux/resource_ext.h:11:
In file included from ../include/linux/slab.h:16:
In file included from ../include/linux/gfp.h:7:
In file included from ../include/linux/mmzone.h:26:
In file included from ../include/linux/kfifo.h:42:
In file included from ../include/linux/scatterlist.h:8:
In file included from ../include/linux/mm.h:1120:
In file included from ../include/linux/huge_mm.h:8:
In file included from ../include/linux/fs.h:13:
In file included from ../include/linux/list_lru.h:14:
In file included from ../include/linux/xarray.h:19:
../include/linux/sched/mm.h:282:6: error: call to undeclared function 'gfpflags_allow_blocking'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  282 |         if (gfpflags_allow_blocking(gfp_flags) &&
      |             ^
../include/linux/sched/mm.h:306:17: error: call to undeclared function 'gfpflags_allow_blocking'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  306 |         might_sleep_if(gfpflags_allow_blocking(gfp_mask));
      |                        ^
In file included from ../arch/arm64/kernel/asm-offsets.c:10:
In file included from ../include/linux/arm_sdei.h:8:
In file included from ../include/acpi/ghes.h:5:
In file included from ../include/acpi/apei.h:9:
In file included from ../include/linux/acpi.h:13:
In file included from ../include/linux/resource_ext.h:11:
In file included from ../include/linux/slab.h:16:
In file included from ../include/linux/gfp.h:7:
In file included from ../include/linux/mmzone.h:26:
In file included from ../include/linux/kfifo.h:42:
In file included from ../include/linux/scatterlist.h:8:
In file included from ../include/linux/mm.h:1120:
In file included from ../include/linux/huge_mm.h:8:
In file included from ../include/linux/fs.h:33:
In file included from ../include/linux/percpu-rwsem.h:7:
In file included from ../include/linux/rcuwait.h:6:
In file included from ../include/linux/sched/signal.h:6:
../include/linux/signal.h:97:11: error: array index 3 is past the end of the array (that has type 'unsigned long[1]') [-Werror,-Warray-bounds]
   97 |                 return (set->sig[3] | set->sig[2] |
      |                         ^        ~
../include/uapi/asm-generic/signal.h:62:2: note: array 'sig' declared here
   62 |         unsigned long sig[_NSIG_WORDS];
      |         ^
In file included from ../arch/arm64/kernel/asm-offsets.c:10:
In file included from ../include/linux/arm_sdei.h:8:
In file included from ../include/acpi/ghes.h:5:
In file included from ../include/acpi/apei.h:9:
In file included from ../include/linux/acpi.h:13:
In file included from ../include/linux/resource_ext.h:11:
In file included from ../include/linux/slab.h:16:
In file included from ../include/linux/gfp.h:7:
In file included from ../include/linux/mmzone.h:26:
In file included from ../include/linux/kfifo.h:42:
In file included from ../include/linux/scatterlist.h:8:
In file included from ../include/linux/mm.h:1120:
In file included from ../include/linux/huge_mm.h:8:
In file included from ../include/linux/fs.h:33:
In file included from ../include/linux/percpu-rwsem.h:7:
In file included from ../include/linux/rcuwait.h:6:
In file included from ../include/linux/sched/signal.h:6:
../include/linux/signal.h:97:25: error: array index 2 is past the end of the array (that has type 'unsigned long[1]') [-Werror,-Warray-bounds]
   97 |                 return (set->sig[3] | set->sig[2] |
      |                                       ^        ~
../include/uapi/asm-generic/signal.h:62:2: note: array 'sig' declared here
   62 |         unsigned long sig[_NSIG_WORDS];
      |         ^
In file included from ../arch/arm64/kernel/asm-offsets.c:10:
In file included from ../include/linux/arm_sdei.h:8:
In file included from ../include/acpi/ghes.h:5:
In file included from ../include/acpi/apei.h:9:
In file included from ../include/linux/acpi.h:13:
In file included from ../include/linux/resource_ext.h:11:
In file included from ../include/linux/slab.h:16:
In file included from ../include/linux/gfp.h:7:
In file included from ../include/linux/mmzone.h:26:
In file included from ../include/linux/kfifo.h:42:
In file included from ../include/linux/scatterlist.h:8:
In file included from ../include/linux/mm.h:1120:
In file included from ../include/linux/huge_mm.h:8:
In file included from ../include/linux/fs.h:33:
In file included from ../include/linux/percpu-rwsem.h:7:
In file included from ../include/linux/rcuwait.h:6:
In file included from ../include/linux/sched/signal.h:6:
../include/linux/signal.h:98:4: error: array index 1 is past the end of the array (that has type 'unsigned long[1]') [-Werror,-Warray-bounds]
   98 |                         set->sig[1] | set->sig[0]) == 0;
      |                         ^        ~
../include/uapi/asm-generic/signal.h:62:2: note: array 'sig' declared here
   62 |         unsigned long sig[_NSIG_WORDS];
      |         ^
In file included from ../arch/arm64/kernel/asm-offsets.c:10:
In file included from ../include/linux/arm_sdei.h:8:
In file included from ../include/acpi/ghes.h:5:
In file included from ../include/acpi/apei.h:9:
In file included from ../include/linux/acpi.h:13:
In file included from ../include/linux/resource_ext.h:11:
In file included from ../include/linux/slab.h:16:
In file included from ../include/linux/gfp.h:7:
In file included from ../include/linux/mmzone.h:26:
In file included from ../include/linux/kfifo.h:42:
In file included from ../include/linux/scatterlist.h:8:
In file included from ../include/linux/mm.h:1120:
In file included from ../include/linux/huge_mm.h:8:
In file included from ../include/linux/fs.h:33:
In file included from ../include/linux/percpu-rwsem.h:7:
In file included from ../include/linux/rcuwait.h:6:
In file included from ../include/linux/sched/signal.h:6:
../include/linux/signal.h:100:11: error: array index 1 is past the end of the array (that has type 'unsigned long[1]') [-Werror,-Warray-bounds]
  100 |                 return (set->sig[1] | set->sig[0]) == 0;
      |                         ^        ~
../include/uapi/asm-generic/signal.h:62:2: note: array 'sig' declared here
   62 |         unsigned long sig[_NSIG_WORDS];
      |         ^
In file included from ../arch/arm64/kernel/asm-offsets.c:10:
In file included from ../include/linux/arm_sdei.h:8:
In file included from ../include/acpi/ghes.h:5:
In file included from ../include/acpi/apei.h:9:
In file included from ../include/linux/acpi.h:13:
In file included from ../include/linux/resource_ext.h:11:
In file included from ../include/linux/slab.h:16:
In file included from ../include/linux/gfp.h:7:
In file included from ../include/linux/mmzone.h:26:
In file included from ../include/linux/kfifo.h:42:
In file included from ../include/linux/scatterlist.h:8:
In file included from ../include/linux/mm.h:1120:
In file included from ../include/linux/huge_mm.h:8:
In file included from ../include/linux/fs.h:33:
In file included from ../include/linux/percpu-rwsem.h:7:
In file included from ../include/linux/rcuwait.h:6:
In file included from ../include/linux/sched/signal.h:6:
../include/linux/signal.h:113:11: error: array index 3 is past the end of the array (that has type 'const unsigned long[1]') [-Werror,-Warray-bounds]
  113 |                 return  (set1->sig[3] == set2->sig[3]) &&
      |                          ^         ~
../include/uapi/asm-generic/signal.h:62:2: note: array 'sig' declared here
   62 |         unsigned long sig[_NSIG_WORDS];
      |         ^
In file included from ../arch/arm64/kernel/asm-offsets.c:10:
In file included from ../include/linux/arm_sdei.h:8:
In file included from ../include/acpi/ghes.h:5:
In file included from ../include/acpi/apei.h:9:
In file included from ../include/linux/acpi.h:13:
In file included from ../include/linux/resource_ext.h:11:
In file included from ../include/linux/slab.h:16:
In file included from ../include/linux/gfp.h:7:
In file included from ../include/linux/mmzone.h:26:
In file included from ../include/linux/kfifo.h:42:
In file included from ../include/linux/scatterlist.h:8:
In file included from ../include/linux/mm.h:1120:
In file included from ../include/linux/huge_mm.h:8:
In file included from ../include/linux/fs.h:33:
In file included from ../include/linux/percpu-rwsem.h:7:
In file included from ../include/linux/rcuwait.h:6:
In file included from ../include/linux/sched/signal.h:6:
../include/linux/signal.h:113:27: error: array index 3 is past the end of the array (that has type 'const unsigned long[1]') [-Werror,-Warray-bounds]
  113 |                 return  (set1->sig[3] == set2->sig[3]) &&
      |                                          ^         ~
../include/uapi/asm-generic/signal.h:62:2: note: array 'sig' declared here
   62 |         unsigned long sig[_NSIG_WORDS];
      |         ^
In file included from ../arch/arm64/kernel/asm-offsets.c:10:
In file included from ../include/linux/arm_sdei.h:8:
In file included from ../include/acpi/ghes.h:5:
In file included from ../include/acpi/apei.h:9:
In file included from ../include/linux/acpi.h:13:
In file included from ../include/linux/resource_ext.h:11:
In file included from ../include/linux/slab.h:16:
In file included from ../include/linux/gfp.h:7:
In file included from ../include/linux/mmzone.h:26:
In file included from ../include/linux/kfifo.h:42:
In file included from ../include/linux/scatterlist.h:8:
In file included from ../include/linux/mm.h:1120:
In file included from ../include/linux/huge_mm.h:8:
In file included from ../include/linux/fs.h:33:
In file included from ../include/linux/percpu-rwsem.h:7:
In file included from ../include/linux/rcuwait.h:6:
In file included from ../include/linux/sched/signal.h:6:
../include/linux/signal.h:114:5: error: array index 2 is past the end of the array (that has type 'const unsigned long[1]') [-Werror,-Warray-bounds]
  114 |                         (set1->sig[2] == set2->sig[2]) &&
      |                          ^         ~
../include/uapi/asm-generic/signal.h:62:2: note: array 'sig' declared here
   62 |         unsigned long sig[_NSIG_WORDS];
      |         ^
In file included from ../arch/arm64/kernel/asm-offsets.c:10:
In file included from ../include/linux/arm_sdei.h:8:
In file included from ../include/acpi/ghes.h:5:
In file included from ../include/acpi/apei.h:9:
In file included from ../include/linux/acpi.h:13:
In file included from ../include/linux/resource_ext.h:11:
In file included from ../include/linux/slab.h:16:
In file included from ../include/linux/gfp.h:7:
In file included from ../include/linux/mmzone.h:26:
In file included from ../include/linux/kfifo.h:42:
In file included from ../include/linux/scatterlist.h:8:
In file included from ../include/linux/mm.h:1120:
In file included from ../include/linux/huge_mm.h:8:
In file included from ../include/linux/fs.h:33:
In file included from ../include/linux/percpu-rwsem.h:7:
In file included from ../include/linux/rcuwait.h:6:
In file included from ../include/linux/sched/signal.h:6:
../include/linux/signal.h:114:21: error: array index 2 is past the end of the array (that has type 'const unsigned long[1]') [-Werror,-Warray-bounds]
  114 |                         (set1->sig[2] == set2->sig[2]) &&
      |                                          ^         ~
../include/uapi/asm-generic/signal.h:62:2: note: array 'sig' declared here
   62 |         unsigned long sig[_NSIG_WORDS];
      |         ^
In file included from ../arch/arm64/kernel/asm-offsets.c:10:
In file included from ../include/linux/arm_sdei.h:8:
In file included from ../include/acpi/ghes.h:5:
In file included from ../include/acpi/apei.h:9:
In file included from ../include/linux/acpi.h:13:
In file included from ../include/linux/resource_ext.h:11:
In file included from ../include/linux/slab.h:16:
In file included from ../include/linux/gfp.h:7:
In file included from ../include/linux/mmzone.h:26:
In file included from ../include/linux/kfifo.h:42:
In file included from ../include/linux/scatterlist.h:8:
In file included from ../include/linux/mm.h:1120:
In file included from ../include/linux/huge_mm.h:8:
In file included from ../include/linux/fs.h:33:
In file included from ../include/linux/percpu-rwsem.h:7:
In file included from ../include/linux/rcuwait.h:6:
In file included from ../include/linux/sched/signal.h:6:
../include/linux/signal.h:115:5: error: array index 1 is past the end of the array (that has type 'const unsigned long[1]') [-Werror,-Warray-bounds]
  115 |                         (set1->sig[1] == set2->sig[1]) &&
      |                          ^         ~
../include/uapi/asm-generic/signal.h:62:2: note: array 'sig' declared here
   62 |         unsigned long sig[_NSIG_WORDS];
      |         ^
In file included from ../arch/arm64/kernel/asm-offsets.c:10:
In file included from ../include/linux/arm_sdei.h:8:
In file included from ../include/acpi/ghes.h:5:
In file included from ../include/acpi/apei.h:9:
In file included from ../include/linux/acpi.h:13:
In file included from ../include/linux/resource_ext.h:11:
In file included from ../include/linux/slab.h:16:
In file included from ../include/linux/gfp.h:7:
In file included from ../include/linux/mmzone.h:26:
In file included from ../include/linux/kfifo.h:42:
In file included from ../include/linux/scatterlist.h:8:
In file included from ../include/linux/mm.h:1120:
In file included from ../include/linux/huge_mm.h:8:
In file included from ../include/linux/fs.h:33:
In file included from ../include/linux/percpu-rwsem.h:7:
In file included from ../include/linux/rcuwait.h:6:
In file included from ../include/linux/sched/signal.h:6:
../include/linux/signal.h:115:21: error: array index 1 is past the end of the array (that has type 'const unsigned long[1]') [-Werror,-Warray-bounds]
  115 |                         (set1->sig[1] == set2->sig[1]) &&
      |                                          ^         ~
../include/uapi/asm-generic/signal.h:62:2: note: array 'sig' declared here
   62 |         unsigned long sig[_NSIG_WORDS];
      |         ^
In file included from ../arch/arm64/kernel/asm-offsets.c:10:
In file included from ../include/linux/arm_sdei.h:8:
In file included from ../include/acpi/ghes.h:5:
In file included from ../include/acpi/apei.h:9:
In file included from ../include/linux/acpi.h:13:
In file included from ../include/linux/resource_ext.h:11:
In file included from ../include/linux/slab.h:16:
In file included from ../include/linux/gfp.h:7:
In file included from ../include/linux/mmzone.h:26:
In file included from ../include/linux/kfifo.h:42:
In file included from ../include/linux/scatterlist.h:8:
In file included from ../include/linux/mm.h:1120:
In file included from ../include/linux/huge_mm.h:8:
In file included from ../include/linux/fs.h:33:
In file included from ../include/linux/percpu-rwsem.h:7:
In file included from ../include/linux/rcuwait.h:6:
In file included from ../include/linux/sched/signal.h:6:
../include/linux/signal.h:118:11: error: array index 1 is past the end of the array (that has type 'const unsigned long[1]') [-Werror,-Warray-bounds]
  118 |                 return  (set1->sig[1] == set2->sig[1]) &&
      |                          ^         ~
../include/uapi/asm-generic/signal.h:62:2: note: array 'sig' declared here
   62 |         unsigned long sig[_NSIG_WORDS];
      |         ^
In file included from ../arch/arm64/kernel/asm-offsets.c:10:
In file included from ../include/linux/arm_sdei.h:8:
In file included from ../include/acpi/ghes.h:5:
In file included from ../include/acpi/apei.h:9:
In file included from ../include/linux/acpi.h:13:
In file included from ../include/linux/resource_ext.h:11:
In file included from ../include/linux/slab.h:16:
In file included from ../include/linux/gfp.h:7:
In file included from ../include/linux/mmzone.h:26:
In file included from ../include/linux/kfifo.h:42:
In file included from ../include/linux/scatterlist.h:8:
In file included from ../include/linux/mm.h:1120:
In file included from ../include/linux/huge_mm.h:8:
In file included from ../include/linux/fs.h:33:
In file included from ../include/linux/percpu-rwsem.h:7:
In file included from ../include/linux/rcuwait.h:6:
In file included from ../include/linux/sched/signal.h:6:
../include/linux/signal.h:118:27: error: array index 1 is past the end of the array (that has type 'const unsigned long[1]') [-Werror,-Warray-bounds]
  118 |                 return  (set1->sig[1] == set2->sig[1]) &&
      |                                          ^         ~
../include/uapi/asm-generic/signal.h:62:2: note: array 'sig' declared here
   62 |         unsigned long sig[_NSIG_WORDS];
      |         ^
In file included from ../arch/arm64/kernel/asm-offsets.c:10:
In file included from ../include/linux/arm_sdei.h:8:
In file included from ../include/acpi/ghes.h:5:
In file included from ../include/acpi/apei.h:9:
In file included from ../include/linux/acpi.h:13:
In file included from ../include/linux/resource_ext.h:11:
In file included from ../include/linux/slab.h:16:
In file included from ../include/linux/gfp.h:7:
In file included from ../include/linux/mmzone.h:26:
In file included from ../include/linux/kfifo.h:42:
In file included from ../include/linux/scatterlist.h:8:
In file included from ../include/linux/mm.h:1120:
In file included from ../include/linux/huge_mm.h:8:
In file included from ../include/linux/fs.h:33:
In file included from ../include/linux/percpu-rwsem.h:7:
In file included from ../include/linux/rcuwait.h:6:
In file included from ../include/linux/sched/signal.h:6:
../include/linux/signal.h:156:1: error: array index 3 is past the end of the array (that has type 'const unsigned long[1]') [-Werror,-Warray-bounds]
  156 | _SIG_SET_BINOP(sigorsets, _sig_or)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/linux/signal.h:137:8: note: expanded from macro '_SIG_SET_BINOP'
  137 |                 a3 = a->sig[3]; a2 = a->sig[2];                         \
      |                      ^      ~
../include/uapi/asm-generic/signal.h:62:2: note: array 'sig' declared here
   62 |         unsigned long sig[_NSIG_WORDS];
      |         ^
In file included from ../arch/arm64/kernel/asm-offsets.c:10:
In file included from ../include/linux/arm_sdei.h:8:
In file included from ../include/acpi/ghes.h:5:
In file included from ../include/acpi/apei.h:9:
In file included from ../include/linux/acpi.h:13:
In file included from ../include/linux/resource_ext.h:11:
In file included from ../include/linux/slab.h:16:
In file included from ../include/linux/gfp.h:7:
In file included from ../include/linux/mmzone.h:26:
In file included from ../include/linux/kfifo.h:42:
In file included from ../include/linux/scatterlist.h:8:
In file included from ../include/linux/mm.h:1120:
In file included from ../include/linux/huge_mm.h:8:
In file included from ../include/linux/fs.h:33:
In file included from ../include/linux/percpu-rwsem.h:7:
In file included from ../include/linux/rcuwait.h:6:
In file included from ../include/linux/sched/signal.h:6:
../include/linux/signal.h:156:1: error: array index 2 is past the end of the array (that has type 'const unsigned long[1]') [-Werror,-Warray-bounds]
  156 | _SIG_SET_BINOP(sigorsets, _sig_or)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../include/linux/signal.h:137:24: note: expanded from macro '_SIG_SET_BINOP'
  137 |                 a3 = a->sig[3]; a2 = a->sig[2];                         \
      |                                      ^      ~
../include/uapi/asm-generic/signal.h:62:2: note: array 'sig' declared here
   62 |         unsigned long sig[_NSIG_WORDS];
      |         ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[3]: *** [../scripts/Makefile.build:116: arch/arm64/kernel/asm-offsets.s] Error 1
make[2]: *** [/home/brokestar/oplus13/common/Makefile:1272: prepare0] Error 2
make[2]: *** Waiting for unfinished jobs....
```
I suspect the first error in the log is due to a **circular dependency**(mmzone->kfifo->scatterlist->mm->mmzone), and the subsequent errors were triggered by this initial one.

2.System fails to boot after successful build with backported kfifo patch (6.16) and other fixes. [Unable to provide dmesg - pstore unavailable on my hardware]

**Comment by firelzrd** [comment]
Thank you for the contribution.
I modified your patch to create this experimental patch, and am testing it now.
Please let me know if it doesn't work at your side.
[0001-kcompressd-unofficial-v0.5-brokestar233.patch.txt](https://github.com/user-attachments/files/20888184/0001-kcompressd-unofficial-v0.5-brokestar233.patch.txt)

**Comment by brokestar233** [comment]
> Thank you for the contribution. I modified your patch to create this experimental patch, and am testing it now. Please let me know if it doesn't work at your side. [0001-kcompressd-unofficial-v0.5-brokestar233.patch.txt](https://github.com/user-attachments/files/20888184/0001-kcompressd-unofficial-v0.5-brokestar233.patch.txt)

I tried your experimental patch, and it still doesn't work (it's still stuck). In the last couple of days I've tried something else, and I've created a patch that allows me to boot the machine normally, but it breaks the original structure so much that I'm not sure if I can guarantee the original functionality.

![Image](https://github.com/user-attachments/assets/294dbe09-9917-4a6a-bdd9-37b21baaa7ea)

[commit#1](https://github.com/brokestar233/android_kernel_common_oneplus_sm8750/commit/11f23d9b767b662969eed64a8d9a7e9a50b2bfa2)
[commit#2](https://github.com/brokestar233/android_kernel_common_oneplus_sm8750/commit/b2e797796d8df74ba359e0236ef2a884d573c771)

**Comment by firelzrd** [comment]
Okay.
I'm going to need to investigate what's going on.
Thank you for taking time for the report!
